name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  casks:
    runs-on: macos-26
    steps:
      - uses: Homebrew/actions/setup-homebrew@main
      - run: brew trust tinecli/tap
      - run: brew style tinecli/tap
      - run: brew audit --cask --strict --online --tap tinecli/tap
